apiVersion: v1
kind: Pod
metadata:
  name: default-cluster-app
  labels:
    clearcloud.co/name: default-cluster-app
spec:
  containers:
    - name: default-cluster-app
      image: clearcloudco/default-cluster-app:0.0.1
      ports:
        - name: http
          containerPort: 4321
---
apiVersion: v1
kind: Service
metadata:
  name: default-cluster-app
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    clearcloud.co/name: default-cluster-app
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: default-cluster-app
spec:
  parentRefs:
    - name: external-http
  hostnames:
    - "cl2-test2-410dacc015a8.clearcloud.app"
  rules:
    - backendRefs:
        - name: default-cluster-app
          port: 80
