apiVersion: v1
kind: Pod
metadata:
  name: default-cluster-app
  labels:
    clearcloud.co/name: default-cluster-app
spec:
  containers:
    - name: default-cluster-app
      image: clearcloudco/default-cluster-app:0.0.1
      ports:
        - name: http
          containerPort: 80
      readinessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 15
        periodSeconds: 10
      livenessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 15
        periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: default-cluster-app
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    clearcloud.co/name: default-cluster-app
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: default-cluster-app
spec:
  parentRefs:
    - name: external-http
  hostnames:
    - "{{.Values.gateway.dnsName}}"
  rules:
    - backendRefs:
        - name: default-cluster-app
          port: 80
  filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: default-cluster-app
  namespace: default
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    config:
      type: HTTP
      httpHealthCheck:
        port: 80
        requestPath: "/"
  targetRef:
    group: ""
    kind: Service
    name: default-cluster-app