apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: clearcloud-apps
  namespace: default
spec:
  interval: 5m0s
  url: {{ .Values.gitRepository.url }}
  secretRef:
    name: git-bearer-token
  ref:
    branch: {{ .Values.gitRepository.branch }}