apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
type: Opaque
data:
  identity: {{.Values.gitRepository.privateKey}}
  known_hosts: |
    {{.Values.gitRepository.knownHost}}
  public_key: {{.Values.gitRepository.publicKey}}